### ISSUE TITLE
Missing abbreviations.txt file after having successfully installed mouse_allen atlas

### ISSUE THREAD

**Issue by niksart** [simonarvin/braincoordinator#1]
After having downloaded the mouse allen atlas, I tried to run braincoordinator but I got the following error. The problem is that the file `abbreviations.txt` is not present in the folder. Do you know how to fix this? Thank you!

```
$ braincoordinator --animal mouse_allen

Brain coordinator initiated
Animal: mouse_allen
Reference: bregma
[Errno 2] No such file or directory: '/home/niksart/braincoordinator/braincoord/lib/python3.8/site-packages/braincoordinator/atlas/mouse_allen//abbreviations.txt'

Atlas not available.
Write '--get [atlas]' to download an atlas.
Or, write '--get list' to list all atlases.
```

**Comment by simonarvin** [comment]
Hi Nicola,

Should be fixed now. Please try again and let me know how it goes.

Best,
Simon

**Comment by niksart** [comment]
Thank you for your answer!

Unfortunately, the same problem persists. I updated the repo with a git pull, deleted and downloaded again the atlas, and then executed again the command above.

When downloading the atlas, it still does not download the `abbreviations.txt` file.

Best,
Nicola

**Comment by simonarvin** [comment]
Are you using a virtual environment? You should reinstall braincoordinator:
`(venv) pip uninstall braincoordinator`
`(venv) pip install .`

**Comment by niksart** [comment]
Ok great, now it works. Thank you!
